export const INGREDIENTS = [
  { value: 'artichoke', label: 'Artichoke' },
  { value: 'bamboo', label: 'Bamboo' },
  { value: 'potato', label: 'Potato' },
  { value: 'broccoli', label: 'Broccoli' },
  { value: 'celery', label: 'Celery' },
  { value: 'onion', label: 'Onion' },
  { value: 'zucchini', label: 'Zucchini' },
  { value: 'chicory', label: 'Chicory' },
  { value: 'garlic', label: 'Garlic' },
  { value: 'squash', label: 'Squash' },
  { value: 'squash', label: 'Squash' },
  { value: 'white squash', label: 'White squash' },
  { value: 'asparagus', label: 'Asparagus' },
  { value: 'brussels sprout', label: 'Brussels sprout' },
  { value: 'kohlrabi', label: 'Kohlrabi' },
  { value: 'horseradish', label: 'Horseradish' },
  { value: 'cauliflower', label: 'Cauliflower' },
  { value: 'eggplant', label: 'Eggplant' },
  { value: 'eggplant', label: 'Eggplant' },
  { value: 'carrot', label: 'Carrot' },
  { value: 'pepper', label: 'Pepper' },
  { value: 'parsnip', label: 'Parsnip' },
  { value: 'parsley', label: 'Parsley' },
  { value: 'chives', label: 'Chives' },
  { value: 'leek', label: 'Leek' },
  { value: 'tomato', label: 'Tomato' },
  { value: 'rhubarb', label: 'Rhubarb' },
  { value: 'beetroot', label: 'Beetroot' },
  { value: 'garden radish', label: 'Garden radish' },
  { value: 'lettuce', label: 'Lettuce' },
  { value: 'spinach', label: 'Spinach' },
  { value: 'rutabaga', label: 'Rutabaga' },
  { value: 'cabbage', label: 'Cabbage' },
  { value: 'radish', label: 'Radish' },
  { value: 'sweet potato', label: 'Sweet potato' },
  { value: 'cassava', label: 'Cassava' },
  { value: 'turnip', label: 'Turnip' },
  { value: 'mangold', label: 'Mangold' },
  { value: 'arugula', label: 'Arugula' },
  { value: 'cress', label: 'Cress' },
  { value: 'ginger', label: 'Ginger' },
  { value: 'broad bean', label: 'Broad bean' },
  { value: 'chickpeas', label: 'Chickpeas' },
  { value: 'lentil', label: 'Lentil' },
  { value: 'bean', label: 'Bean' },
  { value: 'pea', label: 'Pea' },
  { value: 'soybean', label: 'Soybean' },
  { value: 'rice', label: 'Rice' },
  { value: 'apple', label: 'Apple' },
  { value: 'pear', label: 'Pear' },
  { value: 'cherry', label: 'Cherry' },
  { value: 'sour cherry', label: 'Sour cherry' },
  { value: 'plum', label: 'Plum' },
  { value: 'greengage', label: 'Greengage' },
  { value: 'damson plum', label: 'Damson plum' },
  { value: 'mirabelle plum', label: 'Mirabelle plum' },
  { value: 'blackthorn', label: 'Blackthorn' },
  { value: 'apricot', label: 'Apricot' },
  { value: 'peach', label: 'Peach' },
  { value: 'whitebeam', label: 'Whitebeam' },
  { value: 'sorbus', label: 'Sorbus' },
  { value: 'almond', label: 'Almond' },
  { value: 'hazelnut', label: 'Hazelnut' },
  { value: 'walnut', label: 'Walnut' },
  { value: 'chestnut', label: 'Chestnut' },
  { value: 'blueberry', label: 'Blueberry' },
  { value: 'cranberry', label: 'Cranberry' },
  { value: 'blackcurrant', label: 'Blackcurrant' },
  { value: 'redcurrant', label: 'Redcurrant' },
  { value: 'white currant', label: 'White currant' },
  { value: 'gooseberry', label: 'Gooseberry' },
  { value: 'grape', label: 'Grape' },
  { value: 'red raspberry', label: 'Red raspberry' },
  { value: 'berry', label: 'Berry' },
  { value: 'strawberry', label: 'Strawberry' },
  { value: 'pineapple', label: 'Pineapple' },
  { value: 'lemon', label: 'Lemon' },
  { value: 'grapefruit', label: 'Grapefruit' },
  { value: 'mandarin', label: 'Mandarin' },
  { value: 'pomelo', label: 'Pomelo' },
  { value: 'orange', label: 'Orange' },
  { value: 'banana', label: 'Banana' },
  { value: 'date', label: 'Date' },
  { value: 'fig', label: 'Fig' },
  { value: 'pomegranate', label: 'Pomegranate' },
  { value: 'kiwi', label: 'Kiwi' },
  { value: 'quince', label: 'Quince' },
  { value: 'lychee', label: 'Lychee' },
  { value: 'mango', label: 'Mango' },
  { value: 'asian pear', label: 'Asian pear' },
  { value: 'avokado', label: 'Avokado' },
  { value: 'olive', label: 'Olive' },
  { value: 'coconut', label: 'Coconut' },
  { value: 'anise', label: 'Anise' },
  { value: 'star anise', label: 'Star anise' },
  { value: 'basil', label: 'Basil' },
  { value: 'bay leaf', label: 'Bay leaf' },
  { value: 'lemon peel', label: 'Lemon peel' },
  { value: 'cumin', label: 'Cumin' },
  { value: 'caraway', label: 'Caraway' },
  { value: 'black cumin', label: 'Black cumin' },
  { value: 'mustard seed', label: 'Mustard seed' },
  { value: 'chili pepper', label: 'Chili pepper' },
  { value: 'chili', label: 'Chili' },
  { value: 'cardamom', label: 'Cardamom' },
  { value: 'curry', label: 'Curry' },
  { value: 'turmeric', label: 'Turmeric' },
  { value: 'coriander', label: 'Coriander' },
  { value: 'lovage', label: 'Lovage' },
  { value: 'marjoram', label: 'Marjoram' },
  { value: 'mint', label: 'Mint' },
  { value: 'mace', label: 'Mace' },
  { value: 'nutmeg', label: 'Nutmeg' },
  { value: 'allspice', label: 'Allspice' },
  { value: 'oregano', label: 'Oregano' },
  { value: 'pepper', label: 'Pepper' },
  { value: 'chives', label: 'Chives' },
  { value: 'white pepper', label: 'White pepper' },
  { value: 'red pepper', label: 'Red pepper' },
  { value: 'green pepper', label: 'Green pepper' },
  { value: 'fenugreek', label: 'Fenugreek' },
  { value: 'rosemary', label: 'Rosemary' },
  { value: 'cinnamon', label: 'Cinnamon' },
  { value: 'sumac', label: 'Sumac' },
  { value: 'saffron', label: 'Saffron' },
  { value: 'thyme', label: 'Thyme' },
  { value: 'vanilla', label: 'Vanilla' },
  { value: 'ginger', label: 'Ginger' },
  { value: 'sunflower oil', label: 'Sunflower oil' },
  { value: 'olive oil', label: 'Olive oil' },
  { value: 'palm oil', label: 'Palm oil' },
  { value: 'canola oil', label: 'Canola oil' },
  { value: 'butter', label: 'Butter' },
  { value: 'beef', label: 'Beef' },
  { value: 'lamb', label: 'Lamb' },
  { value: 'veal', label: 'Veal' },
  { value: 'mutton', label: 'Mutton' },
  { value: 'pork', label: 'Pork' },
  { value: 'piglet', label: 'Piglet' },
  { value: 'poultry', label: 'Poultry' },
  { value: 'chicken', label: 'Chicken' },
  { value: 'turkey', label: 'Turkey' },
  { value: 'duck', label: 'Duck' },
  { value: 'goose', label: 'Goose' },
  { value: 'fish', label: 'Fish' },
  { value: 'goat meat', label: 'Goat meat' },
  { value: 'deer', label: 'Deer' },
  { value: 'roe deer', label: 'Roe deer' },
  { value: 'rabbit', label: 'Rabbit' },
  { value: 'boar', label: 'Boar' },
  { value: 'carp', label: 'Carp' },
  { value: 'salmon', label: 'Salmon' },
  { value: 'sea bass', label: 'Sea bass' },
  { value: 'seafood', label: 'Seafood' },
  { value: 'bacon', label: 'Bacon' },
  { value: 'sausage', label: 'Sausage' },
  { value: 'ham', label: 'Ham' },
  { value: 'salami', label: 'Salami' },
  { value: 'vienna sausage', label: 'Vienna sausage' },
  { value: 'english bacon', label: 'English bacon' },
  { value: 'smoked meat', label: 'Smoked meat' },
  { value: 'butter', label: 'Butter' },
  { value: 'edam cheese', label: 'Edam cheese' },
  { value: 'balkánský sýr', label: 'Balkánský sýr' },
  { value: 'mozerella', label: 'Mozerella' },
  { value: 'goat cheese', label: 'Goat cheese' },
  {
    value: 'hermelin (czech camambert)',
    label: 'Hermelin (czech camambert)',
  },
  { value: 'gouda', label: 'Gouda' },
  { value: 'cheddar', label: 'Cheddar' },
  { value: 'emmental', label: 'Emmental' },
  { value: 'parmesan', label: 'Parmesan' },
  { value: 'blue cheese', label: 'Blue cheese' },
  { value: 'cottage cheese', label: 'Cottage cheese' },
  { value: 'cream cheese', label: 'Cream cheese' },
  { value: 'camembert', label: 'Camembert' },
  { value: 'ketchup', label: 'Ketchup' },
  { value: 'mayonnaise', label: 'Mayonnaise' },
  { value: 'tartar sauce', label: 'Tartar sauce' },
  { value: 'mustard', label: 'Mustard' },
  { value: 'bechamel', label: 'Bechamel' },
  { value: 'soy sauce', label: 'Soy sauce' },
  { value: 'worcestershire sauce', label: 'Worcestershire sauce' },
  { value: 'chili sauce', label: 'Chili sauce' },
  { value: 'sweet and sour sauce', label: 'Sweet and sour sauce' },
  { value: 'oyster sauce', label: 'Oyster sauce' },
  { value: 'ghee', label: 'Ghee' },
  { value: 'gravy', label: 'Gravy' },
  { value: 'hollandaise sauce', label: 'Hollandaise sauce' },
  { value: 'salsa', label: 'Salsa' },
  { value: 'guacamole', label: 'Guacamole' },
  { value: 'ajika', label: 'Ajika' },
  { value: 'blueberry sauce', label: 'Blueberry sauce' },
  { value: 'apple sauce', label: 'Apple sauce' },
  { value: 'tzatziki', label: 'Tzatziki' },
  { value: 'pesto', label: 'Pesto' },
  { value: 'barbecue sauce', label: 'Barbecue sauce' },
  { value: 'teriyaki', label: 'Teriyaki' },
  { value: 'vinnegar', label: 'Vinnegar' },
  { value: 'balsamic vinegar', label: 'Balsamic vinegar' },
]

export const TAGS = [
  { id: 1, icon: '🌾', label: 'Gluten-free' },
  { id: 2, icon: '☘️', label: 'Bio' },
  { id: 3, icon: '🥑', label: 'Suitable for vegetarians' },
  { id: 4, icon: '🥦', label: 'Suitable for vegans' },
  { id: 5, icon: '🌶️', label: 'Slightly hot' },
  { id: 6, icon: '🌶️🌶️', label: 'Hot' },
  { id: 7, icon: '🌶️🌶️🌶️', label: 'Very hot' },
  { id: 8, icon: '☪️', label: 'Halal' },
  { id: 9, icon: '✡️', label: 'Kosher' },
  { id: 10, icon: '🥩', label: 'Real meat!' },
  { id: 11, icon: '🐷', label: 'Pork' },
]
