export const FETCH_SETTING = 'APP/FETCH_SETTING'

export const REQUESTED_SETTINGS = 'APP/REQUESTED_SETTINGS'
export const REQUESTED_SETTINGS_SUCCEEDED = 'APP/REQUESTED_SETTINGS_SUCCEEDED'
export const REQUESTED_SETTINGS_FAILED = 'APP/REQUESTED_SETTINGS_FAILED'

export const UPDATE_SETTINGS = 'APP/UPDATE_SETTINGS'
