export const LOGIN = 'LOGIN'

export const REQUESTED_LOGIN = 'REQUESTED_LOGIN'
export const REQUESTED_LOGIN_SUCCEEDED = 'REQUESTED_LOGIN_SUCCEEDED'
export const REQUESTED_LOGIN_FAILED = 'REQUESTED_LOGIN_FAILED'

export const REGISTRATION = 'REGISTRATION'

export const REQUESTED_REGISTRATION = 'REQUESTED_REGISTRATION'
export const REQUESTED_REGISTRATION_SUCCEEDED = 'REQUESTED_REGISTRATION_SUCCEEDED'
export const REQUESTED_REGISTRATION_FAILED = 'REQUESTED_REGISTRATION_FAILED'

export const FETCH_USER = 'FETCH_USER'

export const REQUESTED_USER = 'REQUESTED_USER'
export const REQUESTED_USER_SUCCEEDED = 'REQUESTED_USER_SUCCEEDED'
export const REQUESTED_USER_FAILED = 'REQUESTED_USER_FAILED'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const LOGOUT = 'LOGOUT'
