// Fetch Photos
export const FETCH_PHOTOS = 'PHOTOS/FETCH_PHOTOS'
export const REQUESTED_PHOTOS = 'PHOTOS/REQUESTED_PHOTOS'
export const REQUESTED_PHOTOS_SUCCEEDED = 'PHOTOS/REQUESTED_PHOTOS_SUCCEEDED'
export const REQUESTED_PHOTOS_FAILED = 'PHOTOS/REQUESTED_PHOTOS_FAILED'

// Clear Photos
export const CLEAR_PHOTOS = 'PHOTOS/CLEAR_PHOTOS'
