/* Fetch Menus */
export const FETCH_MENUS = 'MENUS/FETCH_MENUS'

export const REQUESTED_MENUS = 'MENUS/REQUESTED_MENUS'
export const REQUESTED_MENUS_SUCCEEDED = 'MENUS/REQUESTED_MENUS_SUCCEEDED'
export const REQUESTED_MENUS_FAILED = 'MENUS/REQUESTED_MENUS_FAILED'

export const ADD_MENU = 'MENUS/ADD_MENU'
export const UPDATE_MENU = 'MENUS/UPDATE_MENU'
export const DELETE_MENU = 'MENUS/DELETE_MENU'

export const CLEAR_MENUS = 'MENU/CLEAR_MENUS'
