/* Fetch Menu */
export const FETCH_MENU = 'MENU/FETCH_MENU'

export const REQUESTED_MENU = 'MENU/REQUESTED_MENU'
export const REQUESTED_MENU_SUCCEEDED = 'MENU/REQUESTED_MENU_SUCCEEDED'
export const REQUESTED_MENU_FAILED = 'MENU/REQUESTED_MENU_FAILED'

/* Save Menu */
export const SAVE_MENU = 'MENU/SAVE_MENU'

export const REQUESTED_SAVE_MENU = 'MENU/REQUESTED_SAVE_MENU'
export const REQUESTED_SAVE_MENU_SUCCEEDED = 'MENU/REQUESTED_SAVE_MENU_SUCCEEDED'
export const REQUESTED_SAVE_MENU_FAILED = 'MENU/REQUESTED_SAVE_MENU_FAILED'

/* Menu */
export const UPDATE_MENU = 'MENU/UPDATE_MENU'
export const CLEAR_MENU = 'MENU/CLEAR_MENU'

/* Category */
export const ADD_CATEGORY = 'MENU/ADD_CATEGORY'
export const UPDATE_CATEGORY = 'MENU/UPDATE_CATEGORY'
export const DELETE_CATEGORY = 'MENU/DELETE_CATEGORY'

/* Dish */
export const ADD_DISH = 'MENU/ADD_DISH'
export const UPDATE_DISH = 'MENU/UPDATE_DISH'
export const DELETE_DISH = 'MENU/DELETE_DISH'
