/* Fetch Menus */
export const FETCH_MENUS = 'MENU/FETCH_MENUS'

export const REQUESTED_MENUS = 'MENU/REQUESTED_MENUS'
export const REQUESTED_MENUS_SUCCEEDED = 'MENU/REQUESTED_MENUS_SUCCEEDED'
export const REQUESTED_MENUS_FAILED = 'MENU/REQUESTED_MENUS_FAILED'
