export const FETCH_ORDERS = 'ORDERS/FETCH_ORDERS'

export const REQUESTED_ORDERS = 'ORDERS/REQUESTED_ORDERS'
export const REQUESTED_ORDERS_SUCCEEDED = 'ORDERS/REQUESTED_ORDERS_SUCCEEDED'
export const REQUESTED_ORDERS_FAILED = 'ORDERS/REQUESTED_ORDERS_FAILED'

export const ADD_ORDER = 'ORDERS/ADD_ORDER'
export const REMOVE_ORDER = 'ORDERS/REMOVE_ORDER'

export const CLEAR_ORDERS = 'ORDERS/CLEAR_ORDERS'
