/* Fetch Settings */
export const FETCH_SETTINGS = 'MENU/FETCH_SETTINGS'

export const REQUESTED_SETTINGS = 'MENU/REQUESTED_SETTINGS'
export const REQUESTED_SETTINGS_SUCCEEDED = 'MENU/REQUESTED_SETTINGS_SUCCEEDED'
export const REQUESTED_SETTINGS_FAILED = 'MENU/REQUESTED_SETTINGS'

export const UPDATE_SETTINGS = 'MENU/UPDATE_SETTINGS'

export const CLEAR_SETTINGS = 'MENU/CLEAR_SETTINGS'
