/* Fetch Settings */
export const FETCH_SETTINGS = 'MENU/FETCH_SETTINGS'

export const REQUESTED_SETTINGS = 'MENU/REQUESTED_SETTINGS'
export const REQUESTED_SETTINGS_SUCCEEDED = 'MENU/REQUESTED_SETTINGS_SUCCEEDED'
export const REQUESTED_SETTINGS_FAILED = 'MENU/REQUESTED_SETTINGS'

/* Update Settings */
export const UPDATE_SETTINGS = 'MENU/UPDATE_SETTINGS'

/* Save Settings */
export const SAVE_SETTINGS = 'MENU/SAVE_SETTINGS'

export const REQUESTED_SAVE_SETTINGS = 'MENU/REQUESTED_SAVE_SETTINGS'
export const REQUESTED_SAVE_SETTINGS_SUCCEEDED = 'MENU/REQUESTED_SAVE_SETTINGS_SUCCEEDED'
export const REQUESTED_SAVE_SETTINGS_FAILED = 'MENU/REQUESTED_SAVE_SETTINGS_FAILED'

/* Clear Settings */
export const CLEAR_SETTINGS = 'MENU/CLEAR_SETTINGS'
